CREATE OR REPLACE TRIGGER TRG_CUSTOMER
BEFORE INSERT OR UPDATE
ON CUSTOMER
REFERENCING OLD as oldROW NEW as newROW
FOR EACH ROW
DECLARE

BEGIN

  IF(:newROW.CREDIT < 0) THEN
    raise_application_error(-20999, 'The Credit ' || :newROW.CREDIT || ' is under the CREDIT');
  END IF;
  
END TRG_CUSTOMER;